Repository Sprint-8-2/KNOCK, pull requests merged in 2024-07, with the labels that each got.

#17 Feature 16 Action Image Optimization 추가
  .github/workflows/calibreapp-image-actions.yml
Labels: 새로운 기능 추가

#15 Feature 14 글로벌css추가
  knock/package-lock.json
  knock/package.json
  knock/src/core/styles/global.scss
Labels: 새로운 기능 추가

#22 Feature 18 reset css추가
  knock/public/index.html
Labels: 새로운 기능 추가

#23 feat: 공통 image 컴포넌트 로직 추가
  knock/package-lock.json
  knock/package.json
  knock/src/App.tsx
  knock/src/core/assets/icon/Arrow-down.svg
  knock/src/core/assets/icon/Arrow-left.svg
  knock/src/core/assets/icon/Arrow-right.svg
  knock/src/core/assets/icon/Arrow-up.svg
  knock/src/core/assets/icon/Close.svg
  knock/src/core/assets/icon/Edit.svg
  knock/src/core/assets/icon/Facebook.svg
  knock/src/core/assets/icon/Kakaotalk.svg
  knock/src/core/assets/icon/Link.svg
  knock/src/core/assets/icon/Messages.svg
  knock/src/core/assets/icon/More.svg
  knock/src/core/assets/icon/Person.svg
  knock/src/core/assets/icon/Rejection.svg
  knock/src/core/assets/icon/arrow-right-1.svg
  knock/src/core/assets/icon/thumbs-down.svg
  knock/src/core/assets/icon/thumbs-up.svg
  knock/src/core/assets/image/Image3.svg
  knock/src/core/assets/image/Profilephoto.svg
  knock/src/core/assets/image/feedHeaderImage.png
  knock/src/core/assets/image/logo-1.svg
  knock/src/core/assets/image/logo.svg
  knock/src/core/assets/image/mainimage.png
  knock/src/core/ui/image/EmptyQuestion.module.scss
  knock/src/core/ui/image/EmptyQuestion.tsx
  knock/src/core/ui/image/FeedHeaderImage.module.scss
  knock/src/core/ui/image/FeedHeaderImage.tsx
  knock/src/core/ui/image/MainImage.module.scss
  knock/src/core/ui/image/MainImage.tsx
  knock/src/core/ui/image/MainLogo.module.scss
  knock/src/core/ui/image/MainLogo.tsx
  knock/src/core/ui/image/ProfilePhoto.tsx
  knock/src/core/ui/image/profilePhoto.module.scss
Labels: 새로운 기능 추가

#24 Feature 8 input추가
  knock/src/core/styles/input.module.scss
  knock/src/core/ui/Input/Input.tsx
Labels: 새로운 기능 추가

#21 Feature 10 dropdown컴포넌트추가
  knock/src/core/styles/dropdown.module.scss
  knock/src/core/ui/Dropdown/Dropdown.tsx
  knock/src/core/ui/Dropdown/DropdownContent.tsx
Labels: 새로운 기능 추가

#27 fix : 공통 image 컴포넌트 로직 수정
  knock/package-lock.json
  knock/src/core/styles/image/EmptyQuestion.module.scss
  knock/src/core/styles/image/FeedHeaderImage.module.scss
  knock/src/core/styles/image/MainImage.module.scss
  knock/src/core/styles/image/MainLogo.module.scss
  knock/src/core/styles/image/ProfileImage.module.scss
  knock/src/core/ui/image/EmptyQuestion.tsx
  knock/src/core/ui/image/FeedHeaderImage.tsx
  knock/src/core/ui/image/MainImage.tsx
  knock/src/core/ui/image/MainLogo.tsx
  knock/src/core/ui/image/ProfileImage.tsx
  knock/src/core/ui/image/ProfilePhoto.tsx
Labels: 버그수정

#30 Feature 2 공통 Box 버튼 컴포넌트 추가 #2
  knock/src/core/ui/buttons/BoxButton/BoxButton.module.scss
  knock/src/core/ui/buttons/BoxButton/BoxButton.tsx
Labels: 새로운 기능 추가

#29 Feature 9 icon컴포넌트추가
  knock/src/core/styles/icon/icon.module.scss
  knock/src/core/ui/Icon/Icon.tsx
Labels: 새로운 기능 추가

#35 Feature 8 공통 input컴포넌트 추가
  knock/src/core/styles/input.module.scss
  knock/src/core/ui/Input/Input.tsx
Labels: 새로운 기능 추가

#37 Feature 12 공통 Textarea 컴포넌트 추가
  knock/src/core/styles/Textarea.module.scss
  knock/src/core/ui/Textarea/Textarea.tsx
Labels: 새로운 기능 추가

#33 Feature 6 공통 Floating버튼 컴포넌트 추가 #6
  knock/package-lock.json
  knock/package.json
  knock/src/core/ui/buttons/FloatingButton/FloatingButton.module.scss
  knock/src/core/ui/buttons/FloatingButton/FloatingButton.tsx
Labels: 새로운 기능 추가

#36 Feature 7 공통 Share버튼컴포넌트 추가
  knock/src/core/assets/icon/Facebook-light.svg
  knock/src/core/assets/icon/Link-light.svg
  knock/src/core/ui/buttons/RoundButton/RoundButton.module.scss
  knock/src/core/ui/buttons/RoundButton/RoundButton.tsx
  knock/src/core/ui/buttons/ShareButtons/FacebookShareButton/FacebookShareButton.module.scss
  knock/src/core/ui/buttons/ShareButtons/FacebookShareButton/FacebookShareButton.tsx
  knock/src/core/ui/buttons/ShareButtons/KakaoShareButton/KakaoShareButton.module.scss
  knock/src/core/ui/buttons/ShareButtons/KakaoShareButton/KakaoShareButton.tsx
  knock/src/core/ui/buttons/ShareButtons/LinkShareButton/LinkShareButton.module.scss
  knock/src/core/ui/buttons/ShareButtons/LinkShareButton/LinkShareButton.tsx
  knock/src/core/ui/buttons/ShareButtons/ShareButtons.module.scss
  knock/src/core/ui/buttons/ShareButtons/ShareButtons.tsx
  knock/src/lib/hooks/useCopyCurrentUrl.ts
  knock/src/lib/hooks/useCopyToClipboard.ts
Labels: 새로운 기능 추가

#39 Feature 31 공통 Badge 컴포넌트 추가
  knock/src/core/styles/badge.module.scss
  knock/src/core/ui/Badge/Badge.tsx
Labels: 새로운 기능 추가

#45 Feature 41 pagination button추가
  knock/src/core/styles/pagination.module.scss
  knock/src/core/ui/Pagenation/Pagination.tsx
  knock/src/core/ui/Pagenation/PaginationButton.tsx
Labels: 새로운 기능 추가

#43 Feature 34 user card컴포넌트추가
  knock/src/core/styles/image/ProfileImage.module.scss
  knock/src/core/styles/usercard/UserCard.module.scss
  knock/src/core/ui/CommonImage/EmptyQuestion.tsx
  knock/src/core/ui/CommonImage/FeedHeaderImage.tsx
  knock/src/core/ui/CommonImage/MainImage.tsx
  knock/src/core/ui/CommonImage/MainLogo.tsx
  knock/src/core/ui/CommonImage/ProfileImage.tsx
  knock/src/core/ui/Icon/Icon.tsx
  knock/src/core/ui/UserCard/UserCard.tsx
Labels: 새로운 기능 추가

#47 Feature 44 api파일추가
  knock/src/core/types/api/Request.ts
  knock/src/core/types/api/Response.ts
  knock/src/lib/api/APIHandler.ts
  knock/src/lib/api/Answers.ts
  knock/src/lib/api/Questions.ts
  knock/src/lib/api/Subject.ts
Labels: 새로운 기능 추가

#55 Fix 53 dropdown외곽선수정
  knock/src/core/styles/dropdown.module.scss
  knock/src/core/ui/Dropdown/Dropdown.tsx
  knock/src/core/ui/Dropdown/DropdownContent.tsx
Labels: 버그수정

#54 Feature 46 공통 메타데이터 추가 #46
  knock/package-lock.json
  knock/package.json
  knock/public/favicon.ico
  knock/src/core/ui/MetaTags/MetaTags.tsx
  knock/src/index.tsx
  knock/src/pages/MainPage/MainPage.tsx
Labels: 새로운 기능 추가

#58 Fix 57 Input컴포넌트 focus로직 scss로 구현 수정
  knock/src/core/styles/input.module.scss
  knock/src/core/ui/Input/Input.tsx
Labels: 버그수정

#59 fix 5 image컴포넌트 수정
  knock/src/core/assets/icon/Hyphen-Arrow-right.svg
  knock/src/core/assets/image/EmptyQuestion.svg
  knock/src/core/assets/image/MainPgaeLogo.svg
  knock/src/core/assets/image/SubPageLogo.svg
  knock/src/core/styles/image/EmptyQuestion.module.scss
  knock/src/core/styles/image/FeedHeaderImage.module.scss
  knock/src/core/styles/image/MainImage.module.scss
  knock/src/core/styles/image/MainLogo.module.scss
  knock/src/core/styles/image/ProfileImage.module.scss
  knock/src/core/ui/CommonIcon/icon.tsx
  knock/src/core/ui/CommonImage/EmptyQuestion.tsx
  knock/src/core/ui/CommonImage/FeedHeaderImage.tsx
  knock/src/core/ui/CommonImage/Image.tsx
  knock/src/core/ui/CommonImage/MainImage.tsx
  knock/src/core/ui/CommonImage/MainLogo.tsx
  knock/src/core/ui/CommonImage/ProfileImage.tsx
  knock/src/core/ui/UserCard/UserCard.tsx
Labels: 버그수정

#67 Feature 66 공통 통합버튼컴포넌트 추가
  knock/package-lock.json
  knock/package.json
  knock/src/core/ui/buttons/BoxButton/BoxButton.tsx
  knock/src/core/ui/buttons/FloatingButton/FloatingButton.module.scss
  knock/src/core/ui/buttons/FloatingButton/FloatingButton.tsx
  knock/src/core/ui/buttons/RoundButton/RoundButton.module.scss
  knock/src/core/ui/buttons/RoundButton/RoundButton.tsx
  knock/src/core/ui/buttons/ShareButtons/FacebookShareButton/FacebookShareButton.tsx
  knock/src/core/ui/buttons/ShareButtons/KakaoShareButton/KakaoShareButton.tsx
  knock/src/core/ui/buttons/ShareButtons/LinkShareButton/LinkShareButton.tsx
  knock/src/core/ui/buttons/UButton/UButton.module.scss
  knock/src/core/ui/buttons/UButton/UButton.tsx
Labels: 새로운 기능 추가

#72 Feature 62 question컴포넌트추가
  knock/src/components/Question/Question.module.scss
  knock/src/components/Question/Question.tsx
  knock/src/lib/hooks/useElapsedTime.ts
Labels: 새로운 기능 추가

#49 Feature 40 공통 toast 컴포넌트 추가
  knock/src/core/styles/toast.module.scss
  knock/src/core/ui/Toast/Toast.tsx
Labels: 새로운 기능 추가

#76 Feature 60 modalPage 컴포넌트 ui 추가
  knock/package-lock.json
  knock/src/core/ui/CommonIcon/icon.tsx
  knock/src/pages/ModalPage.tsx
  knock/src/pages/modalPage.scss
Labels: 새로운 기능 추가

#75 Feature 63 피드카드 피드리스트 컴포넌트 추가
  knock/src/components/FeedCard/FeedCard.module.scss
  knock/src/components/FeedCard/FeedCard.tsx
  knock/src/components/FeedList/FeedList.module.scss
  knock/src/components/FeedList/FeedList.tsx
  knock/src/core/assets/icon/MessagesBrown.svg
Labels: 새로운 기능 추가

#80 Feature 61 질문목록페이지추가
  knock/src/components/QuestionList/QuestionCard.tsx
  knock/src/components/QuestionList/QuestionCardList.module.scss
  knock/src/components/QuestionList/QuestionCardList.tsx
  knock/src/components/QuestionList/QuestionListHeader.module.scss
  knock/src/components/QuestionList/QuestionListHeader.tsx
  knock/src/components/QuestionList/QuestionListMain.module.scss
  knock/src/components/QuestionList/QuestionListMain.tsx
  knock/src/components/QuestionList/QuestionListPagination.module.scss
  knock/src/components/QuestionList/QuestionListPagination.tsx
  knock/src/core/styles/dropdown.module.scss
  knock/src/core/styles/pagination.module.scss
  knock/src/core/styles/usercard/UserCard.module.scss
  knock/src/core/types/api/Request.ts
  knock/src/core/ui/Dropdown/Dropdown.tsx
  knock/src/core/ui/Pagenation/Pagination.tsx
  knock/src/core/ui/Pagenation/PaginationButton.tsx
  knock/src/core/ui/UserCard/UserCard.tsx
  knock/src/lib/api/Subject.ts
  knock/src/lib/hooks/useResizeObserver.ts
  knock/src/pages/QuestionList.tsx
Labels: 새로운 기능 추가

#81 Feature 79 프로필 컴포넌트 추가
  knock/src/components/Profile/Profile.module.scss
  knock/src/components/Profile/Profile.tsx
Labels: 새로운 기능 추가

#84 Feature 73 피드 Answer컴포넌트 추가
  knock/src/components/Answer/Answer.module.scss
  knock/src/components/Answer/Answer.tsx
  knock/src/components/AnswerContent/AnswerContent.module.scss
  knock/src/components/AnswerContent/AnswerContent.tsx
  knock/src/components/AnswerForm/AnswerForm.module.scss
  knock/src/components/AnswerForm/AnswerForm.tsx
  knock/src/components/AnswerModification/AnswerModification.module.scss
  knock/src/components/AnswerModification/AnswerModification.tsx
  knock/src/components/AnswerRejection/AnswerRejection.module.scss
  knock/src/components/AnswerRejection/AnswerRejection.tsx
Labels: 새로운 기능 추가

#86 Feature 65 답변하기 초기 페이지 추가
  knock/src/App.tsx
  knock/src/components/FeedCard/FeedCard.module.scss
  knock/src/components/FeedList/FeedList.tsx
  knock/src/core/styles/answerPage.module.scss
  knock/src/lib/hooks/feed/useQuestionList.tsx
  knock/src/pages/AnswerPage.tsx
Labels: 새로운 기능 추가

#89 Feature 87 페이지라우터추가
  knock/prettierrc.json
  knock/src/App.tsx
  knock/src/pages/MainPage.tsx
  knock/src/pages/NotFound/NotFound.tsx
  knock/src/pages/NotFound/notFound.module.scss
  knock/src/pages/PostPage.tsx
  knock/src/pages/QuestionList.tsx
Labels: 새로운 기능 추가

#83 Feature: modal컴포넌트 api 추가
  knock/src/lib/hooks/useSubmitQuestion.ts
  knock/src/pages/ModalPage.tsx
  knock/src/pages/modalPage.scss
Labels: 새로운 기능 추가

#93 Fix 77 modal 컴포넌트 피드백 수정
  knock/src/lib/hooks/useSubmitQuestion.ts
  knock/src/pages/ModalPage.tsx
  knock/src/pages/modalPage.scss
Labels: 버그수정

#92 Feature 90 질문목록페이지반응형추가
  knock/src/components/QuestionList/QuestionCardList.module.scss
  knock/src/components/QuestionList/QuestionCardList.tsx
  knock/src/components/QuestionList/QuestionListHeader.module.scss
  knock/src/components/QuestionList/QuestionListMain.module.scss
  knock/src/components/QuestionList/QuestionListPagination.tsx
  knock/src/core/styles/pagination.module.scss
  knock/src/core/ui/Pagenation/Pagination.tsx
  knock/src/lib/hooks/useResize.ts
  knock/src/lib/hooks/useResizeObserver.ts
Labels: 버그수정, 새로운 기능 추가

#98 Feature redirects 파일 추가
  knock/netlify.toml
  knock/public/_redirects
Labels: 버그수정, 새로운 기능 추가

#100 Fix 피드 페이지 프로필 이미지 수정
  knock/src/components/Profile/Profile.module.scss
  knock/src/components/Profile/Profile.tsx
Labels: 버그수정

#96 Feature 65 답변하기 개별피드 페이지 추가
  knock/src/components/Answer/Answer.module.scss
  knock/src/components/Answer/Answer.tsx
  knock/src/components/FeedCard/FeedCard.tsx
  knock/src/components/FeedList/FeedList.tsx
  knock/src/components/feed/Answer/Answer.module.scss
  knock/src/components/feed/Answer/Answer.tsx
  knock/src/components/feed/AnswerContent/AnswerContent.module.scss
  knock/src/components/feed/AnswerContent/AnswerContent.tsx
  knock/src/components/feed/AnswerForm/AnswerForm.module.scss
  knock/src/components/feed/AnswerForm/AnswerForm.tsx
  knock/src/components/feed/AnswerModification/AnswerModification.module.scss
  knock/src/components/feed/AnswerModification/AnswerModification.tsx
  knock/src/components/feed/AnswerProfile/AnswerProfile.module.scss
  knock/src/components/feed/AnswerProfile/AnswerProfile.tsx
  knock/src/components/feed/AnswerRejection/AnswerRejection.module.scss
  knock/src/components/feed/AnswerRejection/AnswerRejection.tsx
  knock/src/components/feed/AnswerStateRenderer/AnswerStateRenderer.tsx
  knock/src/components/feed/EmptyFeedListImage/EmptyFeedList.tsx
  knock/src/components/feed/FeedCard/FeedCard.module.scss
  knock/src/components/feed/FeedCard/FeedCard.tsx
  knock/src/components/feed/FeedList/FeedList.module.scss
  knock/src/components/feed/FeedList/FeedList.tsx
  knock/src/core/styles/Textarea.module.scss
  knock/src/core/styles/answerPage.module.scss
  knock/src/core/types/api/Request.ts
  knock/src/core/ui/buttons/UButton/UButton.module.scss
  knock/src/core/ui/buttons/UButton/UButton.tsx
  knock/src/lib/api/APIHandler.ts
  knock/src/lib/api/Answers.ts
  knock/src/lib/hooks/feed/useAddAnswer.ts
  knock/src/lib/hooks/feed/useGetQuestionDetail.ts
  knock/src/lib/hooks/feed/useGetUserInfo.ts
  knock/src/lib/hooks/feed/useQuestionList.ts
  knock/src/lib/hooks/feed/useQuestionList.tsx
  knock/src/lib/hooks/feed/useUpdateEffect.ts
  knock/src/pages/AnswerPage.tsx
  knock/src/pages/ModalPage.tsx
  knock/src/pages/PostPage.module.scss
  knock/src/pages/PostPage.tsx
Labels: 버그수정, 새로운 기능 추가

#112 Feature 108 dropdown추가기능
  knock/src/core/styles/dropdown.module.scss
  knock/src/core/ui/Dropdown/Dropdown.tsx
  knock/src/core/ui/Dropdown/DropdownContent.tsx
  knock/src/lib/hooks/useCloseRef.ts
Labels: 새로운 기능 추가

#113 Feature 107 modal 애니메이션 기능추가
  knock/src/components/Modal/Error.module.scss
  knock/src/components/Modal/Error.tsx
  knock/src/components/Modal/ModaCreateQuestion.module.scss
  knock/src/components/Modal/ModaCreateQuestion.tsx
  knock/src/core/ui/Modal/CommonModal.module.scss
  knock/src/core/ui/Modal/CommonModal.tsx
  knock/src/pages/CreateQuestionPage.module.scss
  knock/src/pages/CreateQuestionPage.tsx
  knock/src/pages/ModalPage.tsx
  knock/src/pages/PostPage.tsx
Labels: 새로운 기능 추가

#120 Fix 로컬스토리지파일 수정
  knock/src/core/ui/buttons/ShareButtons/KakaoShareButton/KakaoShareButton.tsx
  knock/src/lib/hooks/useLoscalStorageUserInfo.ts
  knock/src/lib/hooks/useUserInfo.ts
Labels: 버그수정

#116 Feature 111 공통 UButton컴포넌트 buttonTagType prop 추가
  knock/src/core/ui/buttons/UButton/UButton.tsx
Labels: 새로운 기능 추가

#123 Fix 로컬스토리지 기능 수정
  knock/src/lib/hooks/useLoscalStorageUserInfo.ts
Labels: 버그수정

#124 Fix 118 질문 목록 페이지 드랍다운 수정
  knock/src/components/QuestionList/QuestionListMain.tsx
  knock/src/components/QuestionList/QuestionListPagination.tsx
  knock/src/components/feed/FeedCard/FeedCard.tsx
  knock/src/core/ui/Dropdown/Dropdown.tsx
  knock/src/core/ui/Dropdown/DropdownContent.tsx
Labels: 버그수정

#128 Fix 125 api오류메세지수정
  knock/src/lib/api/APIHandler.ts
Labels: 버그수정

#121 Feature 91 MainPage추가
  knock/src/components/MainPageInput/MainPageInput.tsx
  knock/src/components/MainPageInput/mainPageInput.module.scss
  knock/src/core/styles/input.module.scss
  knock/src/pages/MainPage.module.scss
  knock/src/pages/MainPage.tsx
Labels: 새로운 기능 추가, 도움!!

#97 Feature 74 메인페이지input컴포넌트추가
  knock/src/components/MainPageInput/MainPageInput.tsx
  knock/src/components/MainPageInput/mainPageInput.module.scss
  knock/src/core/styles/input.module.scss
Labels: 새로운 기능 추가

#131 Feature 115 공통 다크모드버튼 추가
  knock/src/App.tsx
  knock/src/core/assets/image/Banner.svg
  knock/src/core/styles/global.scss
  knock/src/core/ui/DarkModeBtn/DarkModeBtn.module.scss
  knock/src/core/ui/DarkModeBtn/DarkModeBtn.tsx
  knock/src/index.css
  knock/src/lib/hooks/useTheme.ts
  knock/src/pages/PostPage.tsx
Labels: 새로운 기능 추가

#129 Feature 91 Main page수정
  knock/src/components/MainPageInput/MainPageInput.tsx
Labels: 버그수정

#132 Feature 110 답변하기 페이지 무한스크롤 추가
  knock/package-lock.json
  knock/package.json
  knock/src/App.tsx
  knock/src/components/feed/FeedList/InfiniteFeedList.tsx
  knock/src/lib/api/Subject.ts
  knock/src/pages/AnswerPage.tsx
  knock/src/pages/PostPage.tsx
Labels: 새로운 기능 추가

#114 Feature 109 답변하기 페이지 LocalStorage 기반 UserInfo 추가
  knock/src/lib/util/localStorageUtil.ts
  knock/src/pages/AnswerPage.tsx
Labels: 새로운 기능 추가

#140 Fix: 115 공통 이미지파일 수정 & input style 수정
  knock/src/core/assets/image/MainBgImg.svg
  knock/src/core/assets/image/feedHeaderImage.png
  knock/src/core/styles/input.module.scss
  knock/src/pages/AnswerPage.tsx
  knock/src/pages/MainPage.tsx
  knock/src/pages/NotFound/NotFound.tsx
Labels: 버그수정

#143 Feature 127 질문목록페이지 리액트쿼리적용
  knock/src/App.tsx
  knock/src/components/QuestionList/QuestionCard.tsx
  knock/src/components/QuestionList/QuestionCardList.tsx
  knock/src/components/QuestionList/QuestionListPagination.tsx
  knock/src/components/SubjectList/SubjectCard.tsx
  knock/src/components/SubjectList/SubjectCardList.module.scss
  knock/src/components/SubjectList/SubjectCardList.tsx
  knock/src/components/SubjectList/SubjectListHeader.module.scss
  knock/src/components/SubjectList/SubjectListHeader.tsx
  knock/src/components/SubjectList/SubjectListMain.module.scss
  knock/src/components/SubjectList/SubjectListMain.tsx
  knock/src/components/SubjectList/SubjectListPagination.module.scss
  knock/src/components/SubjectList/SubjectListPagination.tsx
  knock/src/core/styles/pagination.module.scss
  knock/src/core/styles/usercard/UserCard.module.scss
  knock/src/core/styles/usercard/UserCardSkeleton.module.scss
  knock/src/core/ui/Pagenation/Pagination.tsx
  knock/src/core/ui/UserCard/SkeletonUserCard.tsx
  knock/src/lib/hooks/subjectList/useSubjectList.ts
  knock/src/lib/hooks/subjectList/useSubjectListQuery.ts
  knock/src/lib/hooks/useCopyCurrentUrl.ts
  knock/src/lib/hooks/useCopyToClipboard.ts
  knock/src/pages/QuestionList.tsx
  knock/src/pages/SubjectList.tsx
Labels: 버그수정, 새로운 기능 추가

#144 fix: 모달 레이아웃 수정
  knock/src/components/Modal/ModaCreateQuestion.module.scss
  knock/src/components/Modal/ModaCreateQuestion.tsx
  knock/src/core/styles/Textarea.module.scss
  knock/src/core/ui/Modal/CommonModal.module.scss
  knock/src/core/ui/Modal/CommonModal.tsx
  knock/src/pages/CreateQuestionPage.module.scss
  knock/src/pages/CreateQuestionPage.tsx
Labels: 버그수정

#145 Fix 141 공통 피드백 수정
  knock/public/favicon.ico
  knock/public/logo192.png
  knock/public/logo512.png
  knock/src/components/feed/FeedCard/FeedCard.module.scss
  knock/src/core/styles/Reaction.module.scss
  knock/src/core/styles/badge.module.scss
  knock/src/core/styles/toast.module.scss
  knock/src/core/ui/Reaction/Reaction.tsx
  knock/src/core/ui/buttons/UButton/UButton.module.scss
Labels: 버그수정

#148 Feature 146 질문목록페이지 프로필선택기능추가
  knock/src/components/SubjectList/SubjectListHeader.tsx
  knock/src/components/SubjectList/SubjectListMain.module.scss
  knock/src/components/SubjectList/SubjectListMain.tsx
  knock/src/components/SubjectList/SubjectModalContent.module.scss
  knock/src/components/SubjectList/SubjectModalContent.tsx
  knock/src/core/ui/Dropdown/Dropdown.tsx
  knock/src/core/ui/Modal/CommonModal.module.scss
  knock/src/lib/hooks/useLoscalStorageUserInfo.ts
Labels: 새로운 기능 추가

#152 Fix 147 답변페이지 피드백 수정
  knock/public/index.html
  knock/public/logo192.png
  knock/src/components/feed/ConfirmModal/ConfirmModal.module.scss
  knock/src/components/feed/ConfirmModal/ConfirmModal.tsx
  knock/src/components/feed/FeedList/FeedList.tsx
  knock/src/components/feed/FeedList/InfiniteFeedList.tsx
  knock/src/lib/hooks/feed/useInfiniteQuestionList.ts
  knock/src/pages/AnswerPage.tsx
  knock/src/pages/PostPage.tsx
Labels: 버그수정

#150 Feature 126 질문목록페이지 UI기능추가
  knock/src/components/SubjectList/SubjectCard.tsx
  knock/src/components/SubjectList/SubjectCardList.module.scss
  knock/src/core/styles/usercard/UserCard.module.scss
Labels: 버그수정, 새로운 기능 추가

#149 Feature 142 피드답변하기Context더보기기능추가
  knock/src/components/Question/Question.module.scss
  knock/src/components/Question/Question.tsx
  knock/src/components/feed/Answer/Answer.tsx
  knock/src/components/feed/AnswerContent/AnswerContent.module.scss
  knock/src/components/feed/AnswerContent/AnswerContent.tsx
  knock/src/components/feed/AnswerModification/AnswerModification.module.scss
Labels: 버그수정, 새로운 기능 추가

#153 Fix 카카오톡 공유하기 오류 수정
  knock/src/core/ui/buttons/ShareButtons/KakaoShareButton/KakaoShareButton.tsx
Labels: 버그수정

#155 Fix 154 최종배포 전 오류 수정
  knock/public/index.html
  knock/src/components/Question/Question.tsx
  knock/src/components/SubjectList/SubjectCard.tsx
  knock/src/components/dummy.txt
  knock/src/core/assets/dummy.txt
  knock/src/core/styles/dropdown.module.scss
  knock/src/core/ui/DarkModeBtn/DarkModeBtn.tsx
  knock/src/lib/hooks/dummy.txt
  knock/src/lib/hooks/subjectList/useSubjectList.ts
  knock/src/lib/hooks/useSubmitQuestion.ts
  knock/src/pages/dummy.txt
Labels: 버그수정

#156 Fix 147 답변페이지 피드백 추가 수정
  knock/src/components/feed/AnswerForm/AnswerForm.module.scss
  knock/src/components/feed/AnswerModification/AnswerModification.module.scss
  knock/src/components/feed/AnswerProfile/AnswerProfile.tsx
  knock/src/components/feed/ConfirmModal/ConfirmModal.tsx
  knock/src/core/ui/buttons/UButton/UButton.module.scss
Labels: 버그수정

#160 Hotfix 카카오 공유버튼으로 인한 post페이지 오류 수정
  knock/src/core/ui/buttons/ShareButtons/KakaoShareButton/KakaoShareButton.tsx
Labels: 버그수정

#158 fix: 개별피드페이지 피드백 수정 #157
  knock/src/components/Question/Question.module.scss
  knock/src/components/Question/Question.tsx
  knock/src/components/feed/AnswerContent/AnswerContent.module.scss
  knock/src/components/feed/AnswerContent/AnswerContent.tsx
  knock/src/pages/PostPage.module.scss
Labels: 버그수정

#161 Feature : page설명 애니메이션 추가
  knock/src/components/Animation/AnimatedImage.scss
  knock/src/components/Animation/AnimatedImage.tsx
  knock/src/components/Animation/AnimatedText.scss
  knock/src/components/Animation/AnimatedText.tsx
  knock/src/core/assets/animationImage/Animation-Logo.png
  knock/src/core/assets/animationImage/AnswerComplete.png
  knock/src/core/assets/animationImage/AnswerPageImage.png
  knock/src/core/assets/animationImage/FeedPageImage.png
  knock/src/core/assets/animationImage/ListPageImage.png
  knock/src/core/assets/animationImage/ModalImage.png
  knock/src/core/assets/animationImage/ainmation1.png
  knock/src/core/assets/animationImage/ainmation2.png
  knock/src/core/assets/animationImage/ainmation3.png
  knock/src/core/assets/animationImage/mainPageImage.png
  knock/src/pages/AnimationPage/AnimationPage.scss
  knock/src/pages/AnimationPage/AnimationPage.tsx
  knock/src/pages/AnimationPage/AnswerExplain.scss
  knock/src/pages/AnimationPage/AnswerExplain.tsx
  knock/src/pages/AnimationPage/FeedExplain.scss
  knock/src/pages/AnimationPage/FeedExplain.tsx
  knock/src/pages/AnimationPage/ListPageExplain.scss
  knock/src/pages/AnimationPage/ListPageExplain.tsx
  knock/src/pages/AnimationPage/MainPageExplain.scss
  knock/src/pages/AnimationPage/MainPageExplain.tsx
  knock/src/pages/AnimationPage/StartAnimationPage.scss
  knock/src/pages/AnimationPage/StartAnimationPage.tsx
  knock/src/pages/MainPage.module.scss
  knock/src/pages/MainPage.tsx
Labels: 새로운 기능 추가

#163 Feature 162 카카오 공유하기 내 페이지 / 다른 페이지 공유 시 메세지 변화 추가
  knock/src/components/Profile/Profile.tsx
  knock/src/core/ui/buttons/ShareButtons/KakaoShareButton/KakaoShareButton.tsx
  knock/src/core/ui/buttons/ShareButtons/ShareButtons.tsx
Labels: 새로운 기능 추가

#164 Fix 147 답변페이지 background image 수정
  knock/src/core/styles/answerPage.module.scss
  knock/src/pages/AnswerPage.tsx
Labels: 버그수정

#166 fix: 질문목록페이지 정렬 오류 수정 #165
  knock/src/lib/hooks/subjectList/useSubjectListQuery.ts
Labels: 버그수정

#169 fix: 질문목록페이지 스켈레톤 UI 버그 수정 #168
  knock/src/lib/hooks/subjectList/useSubjectList.ts
Labels: 버그수정

#174 Feature 172 공통 메타태그 수정
  knock/src/App.tsx
  knock/src/core/ui/MetaTags/MetaTags.tsx
  knock/src/pages/AnswerPage.tsx
  knock/src/pages/PostPage.tsx
Labels: 새로운 기능 추가

#175 fix 168 질문 목록 페이지 스켈레톤 UI 요소 개수 오류 수정
  knock/src/lib/hooks/subjectList/useSubjectList.ts
Labels: 버그수정

#177 Fix 173 공통아이콘수정
  knock/package-lock.json
  knock/package.json
  knock/src/components/MainPageInput/MainPageInput.tsx
  knock/src/components/MainPageInput/mainPageInput.module.scss
  knock/src/components/Question/Question.module.scss
  knock/src/components/Question/Question.tsx
  knock/src/components/SubjectList/SubjectListHeader.module.scss
  knock/src/components/SubjectList/SubjectListHeader.tsx
  knock/src/components/SubjectList/SubjectModalContent.module.scss
  knock/src/components/SubjectList/SubjectModalContent.tsx
  knock/src/components/feed/AnswerContent/AnswerContent.module.scss
  knock/src/components/feed/AnswerContent/AnswerContent.tsx
  knock/src/components/feed/FeedList/FeedList.tsx
  knock/src/core/styles/usercard/UserCard.module.scss
  knock/src/core/ui/UserCard/UserCard.tsx
  knock/src/pages/MainPage.module.scss
  knock/src/pages/MainPage.tsx
Labels: 버그수정

#176 Fix 피드 피드리스트 패딩 수정
  knock/src/components/feed/FeedList/FeedList.module.scss
Labels: 버그수정
